language: objective-c

before_install:
    - brew update
    - brew uninstall xctool && brew install xctool --HEAD

script:  xctool -workspace Kimera.xcworkspace -scheme KimeraMobile -configuration Release -sdk iphonesimulator clean build